local _e4NFXgJvMS = game:GetService("UserInputService")
local _nkI2kE9YfV = Instance.new("_nkI2kE9YfV")
local _U7qvBs38wf = Instance.new("Frame")
local _tziXmFPbXk = Instance.new("_tziXmFPbXk")
local _YqnIWLLNyJ = Instance.new("Frame")
local _4GFQQD8dOc = Instance.new("_tziXmFPbXk")
local _HafP0DMnyZ = Instance.new("_HafP0DMnyZ")
local _8Ryc3sMcuG = Instance.new("_8Ryc3sMcuG")
local _PDzK3LfaGL = Instance.new("_HafP0DMnyZ")
local _LogpNnJeXd = Instance.new("_8Ryc3sMcuG")
local _PpSE1FNwm0 = Instance.new("_PpSE1FNwm0")
local _oKuwwdRACo = Instance.new("_oKuwwdRACo")
local _5fNlRtnPLw = Instance.new("_HafP0DMnyZ")
local _1uiWpv8vjV = Instance.new("_8Ryc3sMcuG")
local _l9swEfAvhd = Instance.new("Frame")
local _5GCkDVMdd7 = Instance.new("TextButton")
local _zp2KQf9no9 = Instance.new("_PpSE1FNwm0")
local _ocPB9bVzWv = Instance.new("_tziXmFPbXk")
local _f71gkVLB1Y = Instance.new("_oKuwwdRACo")
local _0dCEYYvNut = Instance.new("_tziXmFPbXk")
local _p8lh0lWJur = Instance.new("Frame")
local _rfbiOvQwFa = Instance.new("TextButton")
local _QbCHgx56gI = Instance.new("_PpSE1FNwm0")
local _nWJjvM5AIp = Instance.new("_tziXmFPbXk")
local _j4OJ6nQkFG = Instance.new("_oKuwwdRACo")
local _Y9R7Ts2P1q = Instance.new("_tziXmFPbXk")
local _Nyf97Ze8U1 = Instance.new("Frame")
local _StBDkAM4zm = Instance.new("TextButton")
local _jM97KjfuGG = Instance.new("_tziXmFPbXk")
local _oL9eR0fCXh = Instance.new("_oKuwwdRACo")
local _OSCQQ77SpR = Instance.new("_PpSE1FNwm0")
local _i3mlCTBpKP = Instance.new("_oKuwwdRACo")
_nkI2kE9YfV.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
_nkI2kE9YfV.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
_U7qvBs38wf.Name = "_U7qvBs38wf"
_U7qvBs38wf.Parent = _nkI2kE9YfV
_U7qvBs38wf.BackgroundColor3 = Color3.fromRGB(16,16,16)
_U7qvBs38wf.BorderSizePixel = 0
_U7qvBs38wf.ClipsDescendants = true
_U7qvBs38wf.Position = UDim2.new(0.292733908,0,0.162809476,0)
_U7qvBs38wf.Size = UDim2.new(0,634,0,500)
_tziXmFPbXk.Parent = _U7qvBs38wf
_YqnIWLLNyJ.Name = "_YqnIWLLNyJ"
_YqnIWLLNyJ.Parent = _U7qvBs38wf
_YqnIWLLNyJ.BackgroundColor3 = Color3.fromRGB(0,0,0)
_YqnIWLLNyJ.BorderSizePixel = 0
_YqnIWLLNyJ.Size = UDim2.new(0,634,0,65)
_4GFQQD8dOc.Parent = _YqnIWLLNyJ
_HafP0DMnyZ.Parent = _YqnIWLLNyJ
_HafP0DMnyZ.BackgroundTransparency = 1
_HafP0DMnyZ.Position = UDim2.new(0.0946372226,0,0.224755853,0)
_HafP0DMnyZ.Size = UDim2.new(0,53,0,25)
_HafP0DMnyZ.Font = Enum.Font.SourceSans
_HafP0DMnyZ.Text = "NzHub"
_HafP0DMnyZ.TextColor3 = Color3.fromRGB(255,255,255)
_HafP0DMnyZ.TextScaled = true
_HafP0DMnyZ.TextWrapped = true
_HafP0DMnyZ.TextXAlignment = Enum.TextXAlignment.Left
_8Ryc3sMcuG.Parent = _HafP0DMnyZ
_8Ryc3sMcuG.MaxTextSize = 25
_PDzK3LfaGL.Parent = _YqnIWLLNyJ
_PDzK3LfaGL.BackgroundTransparency = 1
_PDzK3LfaGL.Position = UDim2.new(0.0946372226,0,0.579999924,0)
_PDzK3LfaGL.Size = UDim2.new(0,80,0,15)
_PDzK3LfaGL.Font = Enum.Font.SourceSans
_PDzK3LfaGL.Text = "Premium Scripts"
_PDzK3LfaGL.TextColor3 = Color3.fromRGB(130,130,130)
_PDzK3LfaGL.TextScaled = true
_PDzK3LfaGL.TextWrapped = true
_PDzK3LfaGL.TextXAlignment = Enum.TextXAlignment.Left
_LogpNnJeXd.Parent = _PDzK3LfaGL
_LogpNnJeXd.MaxTextSize = 15
_PpSE1FNwm0.Parent = _YqnIWLLNyJ
_PpSE1FNwm0.BackgroundTransparency = 1
_PpSE1FNwm0.Position = UDim2.new(0.00788643491,0,0.0769230798,0)
_PpSE1FNwm0.Size = UDim2.new(0,55,0,55)
_PpSE1FNwm0.Image = "rbxassetid://73065257168102"
_oKuwwdRACo.Parent = _PpSE1FNwm0
_5fNlRtnPLw.Parent = _YqnIWLLNyJ
_5fNlRtnPLw.BackgroundTransparency = 1
_5fNlRtnPLw.Position = UDim2.new(0.180000007,0,0.224755853,0)
_5fNlRtnPLw.Size = UDim2.new(0,53,0,25)
_5fNlRtnPLw.Font = Enum.Font.SourceSans
_5fNlRtnPLw.Text = "Studio"
_5fNlRtnPLw.TextColor3 = Color3.fromRGB(182,109,255)
_5fNlRtnPLw.TextScaled = true
_5fNlRtnPLw.TextWrapped = true
_5fNlRtnPLw.TextXAlignment = Enum.TextXAlignment.Left
_1uiWpv8vjV.Parent = _5fNlRtnPLw
_1uiWpv8vjV.MaxTextSize = 25
_l9swEfAvhd.Name = "_l9swEfAvhd"
_l9swEfAvhd.Parent = _YqnIWLLNyJ
_l9swEfAvhd.BackgroundColor3 = Color3.fromRGB(79, 79, 79)
_l9swEfAvhd.BorderSizePixel = 0
_l9swEfAvhd.Position = UDim2.new(0.90957731,0,0.228231102,0)
_l9swEfAvhd.Size = UDim2.new(0,34,0,35)
_5GCkDVMdd7.Name = "_5GCkDVMdd7"
_5GCkDVMdd7.Parent = _l9swEfAvhd
_5GCkDVMdd7.BackgroundColor3 = Color3.fromRGB(0,0,0)
_5GCkDVMdd7.Position = UDim2.new(0.0240817331,0,0.0240816083,0)
_5GCkDVMdd7.Size = UDim2.new(0.95,0,0.95,0)
_5GCkDVMdd7.Text = ""
_zp2KQf9no9.Parent = _5GCkDVMdd7
_zp2KQf9no9.BackgroundTransparency = 1
_zp2KQf9no9.Position = UDim2.new(0.2,0,0.2,0)
_zp2KQf9no9.Rotation = -90
_zp2KQf9no9.Size = UDim2.new(0.6,0,0.6,0)
_zp2KQf9no9.Image = "rbxassetid://83018234146901"
_zp2KQf9no9.ScaleType = Enum.ScaleType.Fit
_ocPB9bVzWv.CornerRadius = UDim.new(0,5)
_ocPB9bVzWv.Parent = _5GCkDVMdd7
_f71gkVLB1Y.Parent = _l9swEfAvhd
_0dCEYYvNut.CornerRadius = UDim.new(0,5)
_0dCEYYvNut.Parent = _l9swEfAvhd
_p8lh0lWJur.Name = "_p8lh0lWJur"
_p8lh0lWJur.Parent = _YqnIWLLNyJ
_p8lh0lWJur.BackgroundColor3 = Color3.fromRGB(79, 79, 79)
_p8lh0lWJur.BorderSizePixel = 0
_p8lh0lWJur.Position = UDim2.new(0.846485794,0,0.228231102,0)
_p8lh0lWJur.Size = UDim2.new(0,34,0,35)
_rfbiOvQwFa.Name = "_5GCkDVMdd7"
_rfbiOvQwFa.Parent = _p8lh0lWJur
_rfbiOvQwFa.BackgroundColor3 = Color3.fromRGB(0,0,0)
_rfbiOvQwFa.Position = UDim2.new(0.0240817331,0,0.0240816083,0)
_rfbiOvQwFa.Size = UDim2.new(0.95,0,0.95,0)
_rfbiOvQwFa.Text = ""
_QbCHgx56gI.Parent = _rfbiOvQwFa
_QbCHgx56gI.BackgroundTransparency = 1
_QbCHgx56gI.Position = UDim2.new(0.2,0,0.2,0)
_QbCHgx56gI.Size = UDim2.new(0.6,0,0.6,0)
_QbCHgx56gI.Image = "rbxassetid://121184243566884"
_QbCHgx56gI.ScaleType = Enum.ScaleType.Fit
_nWJjvM5AIp.CornerRadius = UDim.new(0,5)
_nWJjvM5AIp.Parent = _rfbiOvQwFa
_j4OJ6nQkFG.Parent = _p8lh0lWJur
_Y9R7Ts2P1q.CornerRadius = UDim.new(0,5)
_Y9R7Ts2P1q.Parent = _p8lh0lWJur
_Nyf97Ze8U1.Name = "_Nyf97Ze8U1"
_Nyf97Ze8U1.Parent = _nkI2kE9YfV
_Nyf97Ze8U1.BackgroundTransparency = 1
_Nyf97Ze8U1.Position = UDim2.new(0.0620752722,0,0.137244344,0)
_Nyf97Ze8U1.Size = UDim2.new(0,60,0,60)
_StBDkAM4zm.Name = "_5GCkDVMdd7"
_StBDkAM4zm.Parent = _Nyf97Ze8U1
_StBDkAM4zm.BackgroundColor3 = Color3.fromRGB(30,30,30)
_StBDkAM4zm.Size = UDim2.new(1,0,1,0)
_StBDkAM4zm.Text = ""
_jM97KjfuGG.CornerRadius = UDim.new(0,5)
_jM97KjfuGG.Parent = _StBDkAM4zm
_oL9eR0fCXh.Parent = _StBDkAM4zm
_OSCQQ77SpR.Parent = _StBDkAM4zm
_OSCQQ77SpR.BackgroundTransparency = 1
_OSCQQ77SpR.Size = UDim2.new(1,0,1,0)
_OSCQQ77SpR.Image = "rbxassetid://73065257168102"
_i3mlCTBpKP.Parent = _Nyf97Ze8U1
_5GCkDVMdd7.MouseButton1Click:Connect(_IuC6JR8RxY()
_U7qvBs38wf.Visible = false
end)
_StBDkAM4zm.MouseButton1Click:Connect(_IuC6JR8RxY()
_U7qvBs38wf.Visible = not _U7qvBs38wf.Visible
end)
_Nyf97Ze8U1.Visible = true
local _IuC6JR8RxY MakeDraggable(DragPart, Object)
local _jpGmSkVcT3 = false
local _9ioTQlFTlw
local _MHVAzOJAT8
local _CXiip22OfO
local _IuC6JR8RxY Update(input)
local _w5K6BN0tf1 = input.Position - _MHVAzOJAT8
Object.Position = UDim2.new(
_CXiip22OfO.X.Scale,
_CXiip22OfO.X.Offset + _w5K6BN0tf1.X,
_CXiip22OfO.Y.Scale,
_CXiip22OfO.Y.Offset + _w5K6BN0tf1.Y
)
end
DragPart.InputBegan:Connect(_IuC6JR8RxY(input)
if input.UserInputType == Enum.UserInputType.MouseButton1
or input.UserInputType == Enum.UserInputType.Touch then
_jpGmSkVcT3 = true
_MHVAzOJAT8 = input.Position
_CXiip22OfO = Object.Position
input.Changed:Connect(_IuC6JR8RxY()
if input.UserInputState == Enum.UserInputState.End then
_jpGmSkVcT3 = false
end
end)
end
end)
DragPart.InputChanged:Connect(_IuC6JR8RxY(input)
if input.UserInputType == Enum.UserInputType.MouseMovement
or input.UserInputType == Enum.UserInputType.Touch then
_9ioTQlFTlw = input
end
end)
_e4NFXgJvMS.InputChanged:Connect(_IuC6JR8RxY(input)
if input == _9ioTQlFTlw and _jpGmSkVcT3 then
Update(input)
end
end)
end
MakeDraggable(_YqnIWLLNyJ, _U7qvBs38wf)
MakeDraggable(_StBDkAM4zm, _Nyf97Ze8U1)